[package]
name = "piston-opengex"
version = "0.1.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["opengex", "3D", "data", "model", "piston"]
description = "Meta rules for parsing the OpenGEX format"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/opengex.git"
homepage = "https://github.com/pistondevelopers/opengex"

[lib]
name = "opengex"
path = "src/lib.rs"

[dependencies]
piston_meta = "0.10.2"

[dev-dependencies]
gfx = "0.6.5"
gfx_device_gl = "0.4.1"
piston_window = "0.8.1"
vecmath = "0.1.1"
camera_controllers = "0.4.0"
pistoncore-sdl2_window = "0.5.0"
